--deleting all rows
DELETE FROM DEVICE; 
--DELETE FROM HOTEL;
--DELETE FROM CONFERENCE;
--DELETE FROM ATTENDEE;

--deleting all tables
DROP TABLE DEVICE CASCADE;
--DROP TABLE HOTEL CASCADE;
--DROP TABLE CONFERENCE CASCADE;
--DROP TABLE ATTENDEE CASCADE;
